/* Aeropath Autonomy Flight Testing — client-side demo. Public METAR data comes from AviationWeather.gov.
   FlightLabs / Lido obstacle access requires customer credentials and is intended for a server proxy. */
const $ = id => document.getElementById(id);
// In production these routes belong behind a server-side proxy: API credentials must never be
// embedded in a browser bundle. See `server.example.mjs` for the credential boundary.
const API = { history:'/api/flight-history', obstacles:'/api/obstacles' };
const airports = {
  EHAM:{name:'Amsterdam Schiphol',lat:52.30806,lng:4.76417,heading:54}, EGLL:{name:'London Heathrow',lat:51.4700,lng:-0.4543,heading:90},
  KJFK:{name:'New York JFK',lat:40.6413,lng:-73.7781,heading:44}, KLAX:{name:'Los Angeles',lat:33.9416,lng:-118.4085,heading:70},
  EDDF:{name:'Frankfurt',lat:50.0379,lng:8.5622,heading:70}, LFPG:{name:'Paris Charles de Gaulle',lat:49.0097,lng:2.5479,heading:90},
  LEMD:{name:'Madrid Barajas',lat:40.4983,lng:-3.5676,heading:36}, EDDM:{name:'Munich',lat:48.3538,lng:11.7861,heading:80}, KORD:{name:"Chicago O'Hare",lat:41.9742,lng:-87.9073,heading:100}, WSSS:{name:'Singapore Changi',lat:1.3644,lng:103.9915,heading:20}
};
let map, state={running:false,paused:false,planned:false,progress:0,last:0,route:[],distance:0,dep:null,arr:null,weather:null}, layers={};
function rad(x){return x*Math.PI/180} function deg(x){return x*180/Math.PI}
function dist(a,b){const R=3440.065, dLat=rad(b.lat-a.lat),dLon=rad(b.lng-a.lng);const h=Math.sin(dLat/2)**2+Math.cos(rad(a.lat))*Math.cos(rad(b.lat))*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(h))}
function bearing(a,b){const y=Math.sin(rad(b.lng-a.lng))*Math.cos(rad(b.lat)),x=Math.cos(rad(a.lat))*Math.sin(rad(b.lat))-Math.sin(rad(a.lat))*Math.cos(rad(b.lat))*Math.cos(rad(b.lng-a.lng));return (deg(Math.atan2(y,x))+360)%360}
function project(origin,nm,brg){const d=nm/3440.065,b=rad(brg),la=rad(origin.lat),lo=rad(origin.lng),lat=Math.asin(Math.sin(la)*Math.cos(d)+Math.cos(la)*Math.sin(d)*Math.cos(b)),lng=lo+Math.atan2(Math.sin(b)*Math.sin(d)*Math.cos(la),Math.cos(d)-Math.sin(la)*Math.sin(lat));return {lat:deg(lat),lng:deg(lng)}}
function pointAt(route,t){let total=0;for(let i=1;i<route.length;i++)total+=dist(route[i-1],route[i]);let target=total*t;for(let i=1;i<route.length;i++){let d=dist(route[i-1],route[i]);if(target<=d){return {lat:route[i-1].lat+(route[i].lat-route[i-1].lat)*target/d,lng:route[i-1].lng+(route[i].lng-route[i-1].lng)*target/d,heading:bearing(route[i-1],route[i])};}target-=d}return {...route.at(-1),heading:bearing(route.at(-2),route.at(-1))}}
function makeRoute(dep,arr){const course=bearing(dep,arr), d=dist(dep,arr), gateOut=project(dep,.35,(dep.heading+180)%360), runwayStart=project(dep,.1,(dep.heading+180)%360), runwayEnd=project(dep,1.1,dep.heading), departureFix=project(dep,10,course), arrivalFix=project(arr,10,(bearing(arr,dep)+180)%360), rwyEnd=project(arr,1.1,(arr.heading+180)%360), rwyStart=project(arr,.1,arr.heading), gateIn=project(arr,.35,arr.heading); let cruiseA=project(dep,d*.42,course),cruiseB=project(dep,d*.68,course); return [gateOut,runwayStart,runwayEnd,departureFix,cruiseA,cruiseB,arrivalFix,rwyEnd,rwyStart,gateIn]}
function airportIcon(code){return L.divIcon({className:'airport-label',html:code,iconAnchor:[19,25]})}
function initMap(){map=L.map('map',{zoomControl:false,attributionControl:false}).setView([51.7,2.3],7);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18}).addTo(map);L.control.zoom({position:'bottomright'}).addTo(map)}
function setToast(s){$('mapToast').textContent=s}
function resolveAirport(code){code=code.toUpperCase().trim();return airports[code]||null}
function cachedMetar(code){try{const item=JSON.parse(localStorage.getItem(`aeropath.metar.${code}`));return item&&Date.now()-item.saved<600000?item.value:null}catch{return null}}
async function fetchMetar(code){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),4500);try{const r=await fetch(`https://aviationweather.gov/api/data/metar?ids=${code}&format=json&taf=false&hours=0`,{signal:controller.signal,cache:'no-store'});if(!r.ok)throw Error('METAR unavailable');const data=await r.json(),value=data[0]||null;if(value)localStorage.setItem(`aeropath.metar.${code}`,JSON.stringify({saved:Date.now(),value}));return value}catch(e){return null}finally{clearTimeout(timer)}}
async function fetchHistoricalProfile(dep,arr){try{const r=await fetch(`${API.history}?dep=${encodeURIComponent(dep)}&arr=${encodeURIComponent(arr)}`);if(!r.ok)throw Error();const data=await r.json();return data.route||data.data?.route||null}catch{return null}}
async function fetchObstacles(route){try{const r=await fetch(API.obstacles,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({route})});if(!r.ok)throw Error();return await r.json()}catch{return null}}
function showWeather(metar,code){$('weatherAirport').textContent=code;$('weatherTime').textContent=metar?.obsTime?new Date(metar.obsTime*1000).toISOString().slice(11,16)+'Z':'DEMO DATA';const w=metar?.wdir!==undefined?`${String(metar.wdir).padStart(3,'0')}° / ${metar.wspd||0}kt`:'250° / 14kt';$('wind').textContent=w;$('visibility').textContent=metar?.visib?`${metar.visib} SM`:'10+ SM';$('ceiling').textContent=metar?.vertVis?`${metar.vertVis} ft`:'SCT 3,500';$('temperature').textContent=metar?.temp!==undefined?`${metar.temp}°C`:'16°C';$('weatherSummary').textContent=metar?.rawOb||'Live METAR unavailable — dispatch planning data';$('weatherIcon').textContent=(metar?.wxString||'').includes('TS')?'⚡':'☁'}
function assessRoute(metar){let k=Number(metar?.wspd||14),density=1.17,turb=1.05,angle=1.06,d=state.distance;let windCost=.1*k,clear=(d*((angle+turb)*windCost)/1)*(1+density),storm=0;let effective=3550-(d*.02+windCost);$('rangeValue').textContent=`${Math.max(0,Math.round(effective)).toLocaleString()} NM`;$('costValue').textContent=Math.round(clear+storm).toLocaleString();const alert=k>30;if(alert){$('routeState').textContent='REROUTE';$('routeState').style.color='var(--red)';$('advisoryText').textContent='Wind limit exceeded for B737 routing. A reroute is required.'}else{$('routeState').textContent='NOMINAL';$('routeState').style.color='var(--green)';$('advisoryText').textContent='Cost model clear. Convective buffers are shown on the operational map.'}}
function addStorms(){if(layers.storms)layers.storms.clearLayers();layers.storms=L.layerGroup().addTo(map);if(state.distance<75)return;const mid=pointAt(state.route,.56), sides=[project(mid,12,65),project(mid,20,125)];sides.forEach((s,i)=>{L.circle([s.lat,s.lng],{radius:(i+1)*5200,color:'#ee4f47',weight:2,fillColor:'#ed5048',fillOpacity:.22,dashArray:'5 5'}).bindTooltip(`CONVECTIVE CELL<br>Reflectivity ${i?42:47} dBZ`,{className:'storm-label',permanent:true,direction:'center'}).addTo(layers.storms)})}
function drawFlight(){
  const dep=state.dep,arr=state.arr;
  Object.values(layers).forEach(layer=>layer?.remove?.());
  layers={};
  layers.dep=L.marker([dep.lat,dep.lng],{icon:airportIcon(dep.code)}).bindTooltip(`${dep.name}<br>Departure`,{permanent:true,direction:'top'}).addTo(map);
  layers.arr=L.marker([arr.lat,arr.lng],{icon:airportIcon(arr.code)}).bindTooltip(`${arr.name}<br>Arrival`,{permanent:true,direction:'top'}).addTo(map);
  layers.path=L.polyline(state.route.map(point=>[point.lat,point.lng]),{color:'#0b7e94',weight:2.5,opacity:.86,dashArray:'7 7'}).addTo(map);
  layers.aircraft=L.marker([state.route[0].lat,state.route[0].lng],{
    icon:L.divIcon({className:'aircraft-marker',html:'<div class="plane">✈</div>',iconSize:[30,30],iconAnchor:[15,15]})
  }).addTo(map);
  addStorms();
  map.fitBounds(L.latLngBounds([[dep.lat,dep.lng],[arr.lat,arr.lng]]).pad(.3));
}
function phase(t){if(t<.06)return 'TAXI OUT';if(t<.13)return 'TAKEOFF / CLIMB';if(t<.8)return 'CRUISE';if(t<.92)return 'APPROACH / LANDING';return 'TAXI IN'}
function update(t){const p=pointAt(state.route,t),ph=phase(t),alt=t<.13?Math.round(39000*Math.max(0,(t-.06)/.07)):t>.8?Math.round(39000*Math.max(0,(.92-t)/.12)):39000;const sp=ph.includes('TAXI')?Math.round(12+(t>.92?8:0)):ph.includes('TAKEOFF')?Math.round(150+(t-.06)*3000):ph.includes('APPROACH')?165:455;layers.aircraft.setLatLng([p.lat,p.lng]);layers.aircraft.getElement()?.querySelector('.plane')?.style.setProperty('transform',`rotate(${p.heading-45}deg)`);$('phaseText').textContent=ph;$('phaseDot').classList.add('active');$('altitude').innerHTML=`${alt.toLocaleString()} <em>FT</em>`;$('speed').innerHTML=`${sp} <em>KT</em>`;$('heading').innerHTML=`${String(Math.round(p.heading)).padStart(3,'0')}<em>°</em>`;$('remaining').innerHTML=`${Math.round(state.distance*(1-t))} <em>NM</em>`;$('progress').style.width=`${t*100}%`;$('positionDot').style.left=`${t*100}%`;$('timelinePhase').textContent=ph;$('elapsed').textContent=`${String(Math.floor(t*32)).padStart(2,'0')}:${String(Math.floor((t*32%1)*60)).padStart(2,'0')}`;$('eta').textContent=t<1?`ETA ${Math.max(0,Math.ceil((1-t)*32))} MIN`:'ON BLOCK';}
function animate(now){if(state.running&&!state.paused){if(!state.last)state.last=now;state.progress+=((now-state.last)/1000)/55;state.last=now;if(state.progress>=1){state.progress=1;state.running=false;$('startButton').disabled=false;$('pauseButton').disabled=true;$('pauseButton').textContent='Ⅱ Pause';setToast('Arrival complete — B737 is on stand.')}update(state.progress)}requestAnimationFrame(animate)}
async function plan(){const dc=$('departure').value.toUpperCase(),ac=$('arrival').value.toUpperCase();let dep=resolveAirport(dc),arr=resolveAirport(ac);if(!dep||!arr||dc===ac){setToast(!dep||!arr?'Enter a supported airport pair. Try EHAM, EGLL, EDDF, LFPG, KJFK, KLAX, KORD, EDDM, LEMD or WSSS.':'Departure and arrival must differ.');return false}state.dep={...dep,code:dc};state.arr={...arr,code:ac};state.route=makeRoute(state.dep,state.arr);state.distance=dist(dep,arr);state.progress=0;state.last=0;state.planned=true;$('startButton').disabled=false;$('routeLabel').textContent=`${dc} ⟶ ${ac}`;$('weatherAirport').textContent=dc;drawFlight();update(0);setToast(`Dispatch plan loaded • ${Math.round(state.distance)} NM • collecting live METAR`);const cached=cachedMetar(dc);if(cached){showWeather(cached,dc);$('weatherTime').textContent='CACHED';assessRoute(cached)}fetchMetar(dc).then(metar=>{state.weather=metar||cached;showWeather(state.weather,dc);assessRoute(state.weather);setToast(metar?`Live METAR received from Aviation Weather Service • ${Math.round(state.distance)} NM route ready`:'Route ready • METAR source temporarily unavailable; planning values displayed')});fetchHistoricalProfile(dc,ac).then(history=>{if(!state.running&&Array.isArray(history)&&history.length>3){const historic=history.map(p=>({lat:Number(p.lat||p.latitude),lng:Number(p.lng||p.longitude)})).filter(p=>Number.isFinite(p.lat)&&Number.isFinite(p.lng));if(historic.length>3){state.route=[makeRoute(state.dep,state.arr)[0],...historic,makeRoute(state.dep,state.arr).at(-1)];drawFlight();update(0)}}});fetchObstacles(state.route);return true}
async function findRoute(){const button=$('findRouteButton');button.disabled=true;button.textContent='Calculating route…';setToast('Calculating route, runway alignment, weather and hazard constraints…');try{const [planned]=await Promise.all([plan(),new Promise(resolve=>setTimeout(resolve,500))]);if(!planned)setToast('Route was not calculated. Check both ICAO codes and try again.')}catch(error){console.error(error);state.planned=false;$('startButton').disabled=true;setToast('Route calculation failed. Please try again.')}finally{button.disabled=false;button.innerHTML='<span>⌁</span> Find route'}}
function reset(){if(!state.planned){setToast('Find a route before resetting the flight.');return}state.running=false;state.paused=false;state.progress=0;state.last=0;$('startButton').disabled=false;$('pauseButton').disabled=true;$('pauseButton').textContent='Ⅱ Pause';update(0);setToast('Flight reset to departure gate — aligned for taxi.')}
function invalidateRoute(){if(!state.planned)return;state.planned=false;state.running=false;state.route=[];$('startButton').disabled=true;$('pauseButton').disabled=true;$('phaseText').textContent='Route needs planning';$('phaseDot').classList.remove('active');setToast('Airport changed — select Find route to build a new dispatch plan.')}
$('findRouteButton').onclick=plan;$('startButton').onclick=()=>{if(!state.planned){setToast('Find a route before starting the simulation.');return}state.running=true;state.paused=false;state.last=0;$('startButton').disabled=true;$('pauseButton').disabled=false;setToast('Pushback approved — following historical gate-to-gate profile.')};$('pauseButton').onclick=()=>{state.paused=!state.paused;$('pauseButton').textContent=state.paused?'▶ Resume':'Ⅱ Pause';setToast(state.paused?'Simulation paused.':'Simulation resumed.')};$('resetButton').onclick=reset;['departure','arrival'].forEach(id=>$(id).addEventListener('input',invalidateRoute));
$('findRouteButton').onclick=findRoute;setInterval(()=>{$('clock').textContent=new Date().toISOString().slice(11,19)+' UTC'},1000);initMap();setToast('Enter departure and arrival ICAO codes, then select Find route.');requestAnimationFrame(animate);
